### ISSUE TITLE
I have a problem with default User attribute on ubuntu 14.04

### ISSUE THREAD

**Issue by cvl-skubriev** [TD-4242/zabbix-agent#4]
I have a problem with default User attribute on ubuntu 14.04

I try to use this cookbook, but faced with zabbix_agentd starting error:

```
zabbix_agentd [16255]: unknown parameter [User] in config file [/etc/zabbix/zabbix_agentd.conf], line 22
```

How to override this default attribute or unset it with role ?

I found some solutions:

#### First - is use this code
```
node.automatic_attrs[:foo].delete(:bar) rescue nil
```
I cannot understand where is to write it?

#### Second - is to use chef 12 and `remove_attribute`

https://tickets.opscode.com/browse/CHEF-5188

I cannot use chef 12 and this solution, because I need to reorganise all infrastructure.

What do you think ? How to unset this default attribute without forking and patching cookbook ?

I use zabbix_agent 2.2. I cannot find this parametr in the doc:
https://www.zabbix.com/documentation/2.2/manual/appendix/config/zabbix_agentd
Same as in 2.0: https://www.zabbix.com/documentation/2.0/manual/appendix/config/zabbix_agentd

This is cookbook is outdated ?

**Comment by cvl-skubriev** [comment]
I am sorry to bother you.
I was succesfully solved all problems by upgrade zabbix-agent version to 1:2.4.4-1+trusty.

**Comment by TD-4242** [comment]
No problem at all.  glad you were able to fix it.  I've been testing with 2.4.x and did notice that older versions of the Zabbix agent didn't support the User flag.  What version of the cookbook are you using.  It shouldn't be setting the Userflag at all on the older versions because of:
<pre>
if node['zabbix']['agent']['version'].match(/2\.4\..*/)
  default['zabbix']['agent']['conf']['User']          = default['zabbix']['agent']['user']
end
</pre>
in the attributes/default.rb file.

**Comment by cvl-skubriev** [comment]
I did not find this condition in attributes (inattentive).

This don't work on ubuntu 14.04 latest updates, zabbix 2.2.2+dfsg-1ubuntu1, and cookbook version 0.12.0. 
I don't know why this condition is not working as it should. 

What is the difference beetwen `default['zabbix']['agent']['conf']['User']` and `default['zabbix']['agent']['user']` ? 

As I understand `default['zabbix']['agent']['conf']['User']` - is the option in agent configuration file.
In that case what's mean the `default['zabbix']['agent']['user']` ?

**Comment by TD-4242** [comment]
`default['zabbix']['agent']['user']` us the user that gets created by chef to run the service as, `default['zabbix']['agent']['conf']['User']` gets written to the configuration file and is a new field in 2.4.x  They should be in all cases I can think of the same so the default is to assign agent-user to conf-user.

Because `default['zabbix']['agent']['user']` is used outside of zabbix_agent.conf file I've kept is as a separate attribute.  All attributes under default['zabbix']['agent']['conf'] get written to the conf file template as *key*=*value*
